[package]
name = "py_gauge_mc"
version = "0.1.0"
authors = ["Sumner Hearth <sumnernh@gmail.com>"]
edition = "2021"

[features]
default = ["gpu-wgpu"]
gpu-wgpu = ["gaugemc/gpu-wgpu", "pollster"]

[lib]
name = "py_gauge_mc"
crate-type = ["cdylib"]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

[dependencies]
pollster = {version="^0.2",optional=true }

[dependencies.gaugemc]
git = "https://github.com/Renmusxd/GaugeMC"
branch = "BleedingEdgeWGPU"
features = ["gpu-wgpu"]

[dependencies.pyo3]
version = "^0.16"
features = ["extension-module"]

[dependencies.numpy]
version = "^0.16"
