[package]
name = "py_gauge_mc"
version = "0.1.0"
authors = ["Sumner Hearth <sumnernh@gmail.com>"]
edition = "2021"

[lib]
name = "py_gauge_mc"
crate-type = ["cdylib"]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

[dependencies]
gaugemc = {path = "../GaugeTheoryMC"}

[dependencies.pyo3]
version = ">=0.15"
features = ["extension-module"]

[dependencies.numpy]
version = ">=0.15"
features = ["rayon"]

[dependencies.ndarray]
version = "*"
features = ["rayon"]